CREATE TABLE IF NOT EXISTS con_contract (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    contract_number VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    contract_type VARCHAR(64) NOT NULL,
    service_type VARCHAR(64) NOT NULL,
    customer_credit_level VARCHAR(16) NULL,
    owner_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CNY',
    content LONGTEXT NOT NULL,
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    end_date DATE NULL,
    content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_con_contract_number (tenant_id, contract_number),
    KEY idx_con_contract_status (tenant_id, status),
    KEY idx_con_contract_owner (tenant_id, owner_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS con_contract_lifecycle_event (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    contract_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    from_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    to_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    actor_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    reason VARCHAR(1000) NULL,
    approval_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    workflow_id VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
    idempotency_key VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_con_lifecycle_idempotency (idempotency_key),
    KEY idx_con_lifecycle_contract (tenant_id, contract_id, occurred_at),
    CONSTRAINT fk_con_lifecycle_contract FOREIGN KEY (contract_id) REFERENCES con_contract (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS con_approval_rule (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(128) NOT NULL,
    priority INT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    expression_json JSON NOT NULL,
    nodes_json JSON NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (id),
    KEY idx_con_rule_match (tenant_id, enabled, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS con_approval_instance (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    contract_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    applicant_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    from_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    target_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    reason VARCHAR(1000) NULL,
    rule_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    rule_version BIGINT UNSIGNED NULL,
    content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    nodes_json JSON NOT NULL,
    runtime_state_json JSON NULL,
    current_node_index INT NOT NULL DEFAULT 0,
    temporal_workflow_id VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    temporal_run_id VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    completion_applied BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_con_approval_workflow (temporal_workflow_id),
    KEY idx_con_approval_contract (tenant_id, contract_id, created_at),
    KEY idx_con_approval_status (tenant_id, status, created_at),
    CONSTRAINT fk_con_approval_contract FOREIGN KEY (contract_id) REFERENCES con_contract (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS con_approval_task (
    approval_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    node_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    assignee_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    node_index INT NOT NULL,
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    PRIMARY KEY (approval_id, node_id, assignee_user_id),
    KEY idx_con_task_assignee (assignee_user_id, status),
    CONSTRAINT fk_con_task_approval FOREIGN KEY (approval_id) REFERENCES con_approval_instance (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS con_approval_action (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    approval_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    contract_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    node_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    command_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    action VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    actor_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    comment VARCHAR(2000) NULL,
    payload_json JSON NULL,
    occurred_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_con_action_command (command_id),
    KEY idx_con_action_approval (tenant_id, approval_id, occurred_at),
    CONSTRAINT fk_con_action_approval FOREIGN KEY (approval_id) REFERENCES con_approval_instance (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS con_notification_outbox (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    tenant_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    recipient_key VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    recipient_user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    recipient_role_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    notification_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    contract_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    approval_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    dedupe_key VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    delivery_status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'pending',
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(3) NOT NULL,
    delivered_at DATETIME(3) NULL,
    last_error VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_con_notification_dedupe (tenant_id, recipient_key, dedupe_key),
    KEY idx_con_notification_delivery (delivery_status, next_attempt_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
