const API_BASE_URL = (import.meta.env?.VITE_API_BASE_URL || '/api/v1').replace(/\/$/, '')

export class IamError extends Error {
  constructor(message, options = {}) {
    super(message)
    this.name = 'IamError'
    this.status = options.status || 0
    this.code = options.code || ''
    this.traceId = options.traceId || ''
  }
}

async function readBody(response) {
  const contentType = response.headers.get('content-type') || ''
  if (contentType.includes('application/json')) {
    try {
      return await response.json()
    } catch {
      return {}
    }
  }
  const text = await response.text()
  return text ? { message: text } : {}
}

async function request(path, options = {}) {
  let response
  try {
    response = await fetch(`${API_BASE_URL}${path}`, {
      ...options,
      credentials: 'include',
      headers: {
        Accept: 'application/json',
        ...(options.body ? { 'Content-Type': 'application/json' } : {}),
        ...(options.headers || {}),
      },
    })
  } catch {
    throw new IamError('无法连接 IAM 服务，请确认后端服务已启动。', { code: 'NETWORK_ERROR' })
  }
  const body = await readBody(response)
  if (!response.ok) {
    throw new IamError(body?.message || 'IAM 请求失败。', {
      status: response.status,
      code: body?.code,
      traceId: body?.request_id || body?.trace_id || body?.traceId,
    })
  }
  return body?.data
}

function pageQuery(parameters = {}) {
  const search = new URLSearchParams()
  Object.entries(parameters).forEach(([key, value]) => {
    if (value === undefined || value === null || value === '') return
    search.set(key, String(value))
  })
  const encoded = search.toString()
  return encoded ? `?${encoded}` : ''
}

function normalize(value) {
  if (!value || typeof value !== 'object') {
    return { items: [], total: 0, page: 1, pageSize: 20 }
  }
  return {
    items: Array.isArray(value.items) ? value.items : [],
    total: Number(value.total || 0),
    page: Number(value.page || 1),
    pageSize: Number(value.page_size || 20),
  }
}

// --- Users ---

export function listUsers({ page = 1, pageSize = 50, keyword = '', status = '' } = {}) {
  return request(`/users${pageQuery({ page, page_size: pageSize, keyword, 'filter[status]': status })}`).then(normalize)
}

export function getUser(userId) {
  return request(`/users/${encodeURIComponent(userId)}`)
}

export function createUser({ displayName, email = null, mobile = null, status = 'ACTIVE' }) {
  return request('/users', {
    method: 'POST',
    body: JSON.stringify({ display_name: displayName, email, mobile, status }),
  })
}

// createUsersBatch creates up to 100 ordinary users atomically. Employee numbers and the default
// ordinary-user role binding are generated by the backend for every item.
export function createUsersBatch(items) {
  return request('/users/batch', {
    method: 'POST',
    body: JSON.stringify({
      items: items.map((item) => ({
        display_name: item.displayName,
        email: item.email,
        mobile: item.mobile,
        status: item.status || 'ACTIVE',
      })),
    }),
  })
}


export function updateUser({ userId, displayName, employeeNo = '', email = '', mobile = '', status, version }) {
  return request(`/users/${encodeURIComponent(userId)}`, {
    method: 'PATCH',
    body: JSON.stringify({ display_name: displayName, employee_no: employeeNo, email, mobile, status, version }),
  })
}

// deleteUser performs a business deletion. The backend disables and hides associated login accounts
// and memberships, and revokes active sessions atomically. The version field prevents stale writes.
export function deleteUser({ userId, version }) {
  return request(`/users/${encodeURIComponent(userId)}`, {
    method: 'DELETE',
    body: JSON.stringify({ version }),
  })
}

// --- Accounts ---

export function listAccounts({ page = 1, pageSize = 50, keyword = '', status = '' } = {}) {
  return request(`/accounts${pageQuery({ page, page_size: pageSize, keyword, 'filter[status]': status })}`).then(normalize)
}

export function createLocalAccount({ userId, accountName, initialPassword }) {
  return request('/accounts', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, account_name: accountName, initial_password: initialPassword }),
  })
}

export function updateAccountStatus({ accountId, status, version }) {
  return request(`/accounts/${encodeURIComponent(accountId)}`, {
    method: 'PATCH',
    body: JSON.stringify({ status, version }),
  })
}

// resetAccountPassword asks the server to generate a one-time temporary password.
export function resetAccountPassword({ accountId, version }) {
  return request(`/accounts/${encodeURIComponent(accountId)}/password/reset`, {
    method: 'POST',
    body: JSON.stringify({ version }),
  })
}

// --- Org Units ---

export function listOrgUnits({ page = 1, pageSize = 100, keyword = '', status = 'ACTIVE' } = {}) {
  return request(`/org-units${pageQuery({ page, page_size: pageSize, keyword, 'filter[status]': status })}`).then(normalize)
}

export function createOrgUnit({ parentId = null, name, sortOrder = 0 }) {
  return request('/org-units', {
    method: 'POST',
    body: JSON.stringify({ parent_id: parentId, name, sort_order: sortOrder }),
  })
}

// --- Positions ---

export function listPositions({ page = 1, pageSize = 100, keyword = '', status = 'ACTIVE' } = {}) {
  return request(`/positions${pageQuery({ page, page_size: pageSize, keyword, 'filter[status]': status })}`).then(normalize)
}

export function createPosition({ orgUnitId, name }) {
  return request('/positions', {
    method: 'POST',
    body: JSON.stringify({ org_unit_id: orgUnitId, name }),
  })
}

// --- Memberships ---

export function listMemberships({ page = 1, pageSize = 50, keyword = '', status = '' } = {}) {
  return request(`/memberships${pageQuery({ page, page_size: pageSize, keyword, 'filter[status]': status })}`).then(normalize)
}

export function createMembership({ userId, orgUnitId, positionId, membershipType = 'PRIMARY', effectiveFrom = null, effectiveTo = null }) {
  return request('/memberships', {
    method: 'POST',
    body: JSON.stringify({
      user_id: userId,
      org_unit_id: orgUnitId,
      position_id: positionId,
      membership_type: membershipType,
      effective_from: effectiveFrom,
      effective_to: effectiveTo,
    }),
  })
}

export function updateMembershipStatus({ membershipId, status, version }) {
  return request(`/memberships/${encodeURIComponent(membershipId)}`, {
    method: 'PATCH',
    body: JSON.stringify({ status, version }),
  })
}

// --- External identities ---

export function listIdentityProviders({ page = 1, pageSize = 100 } = {}) {
  return request(`/identity-providers${pageQuery({ page, page_size: pageSize })}`).then(normalize)
}

export function listUserExternalIdentities(userId) {
  return request(`/users/${encodeURIComponent(userId)}/external-identities`).then((value) => {
    if (Array.isArray(value)) return value
    return Array.isArray(value?.items) ? value.items : []
  })
}

export function bindUserExternalIdentity({ userId, providerCode, externalSubject }) {
  return request(`/users/${encodeURIComponent(userId)}/external-identities`, {
    method: 'POST',
    body: JSON.stringify({ provider_code: providerCode, external_subject: externalSubject }),
  })
}

export function unbindUserExternalIdentity({ userId, bindingId, version }) {
  return request(`/users/${encodeURIComponent(userId)}/external-identities/${encodeURIComponent(bindingId)}`, {
    method: 'DELETE',
    body: JSON.stringify({ version }),
  })
}
