import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('Settlement view exposes the first-phase financial workflow without mock records', async () => {
  const source = await readFile(new URL('./views/SettlementView.vue', import.meta.url), 'utf8')
  for (const section of ['dashboard', 'receivables', 'invoices', 'receipts', 'allocations', 'dunning', 'tasks']) assert.match(source, new RegExp(`'${section}'`))
  assert.match(source, /confirmReceivablePlan/)
  assert.match(source, /createReceiptAllocation/)
  assert.match(source, /registerManualInvoice/)
  assert.match(source, /item\.issue_channel === 'MANUAL'/)
  assert.match(source, /can\('settlement\.invoice\.request'\)/)
  assert.match(source, /can\('settlement\.invoice\.approve'\)/)
  assert.match(source, /can\('settlement\.invoice\.issue'\)/)
  assert.match(source, /submitPlanConfirmation/)
  assert.match(source, /submitInvoiceReview/)
  assert.match(source, /回款匹配建议/)
  assert.match(source, /uploadInvoiceDocument/)
  assert.match(source, /submitRedFlush/)
  assert.match(source, /reviewRedFlush/)
  assert.match(source, /待财务复核/)
  assert.match(source, /match_confidence: match\.score/)
  assert.match(source, /原发票在收到有效税控回执前仍保持已开具状态/)
  assert.match(source, /receiptCustomers/)
  assert.match(source, /collectionStatusLabel/)
  assert.match(source, /receivableInvoiceStatusLabel/)
  assert.match(source, /exportAgingReceivables/)
  assert.doesNotMatch(source, /正式账龄报表与受控导出需接入/)
  assert.match(source, /logoutCurrentSession/)
  assert.match(source, /closeSubsystemTabOrFallback/)
  assert.match(source, /getSettlementSession/)
  assert.match(source, /sessionDisplayName/)
  assert.match(source, /统一认证已接入/)
  assert.doesNotMatch(source, />平台管理员</)
  assert.doesNotMatch(source, />超级管理员</)
  assert.match(source, /reason: "session-ended"/)
  assert.match(source, /:disabled="isLoggingOut"/)
  assert.match(source, /modules\/platform\/styles\/console\.css/)
  assert.match(source, /console-page settlement-shell/)
  assert.match(source, /console-sidebar settlement-sidebar/)
  assert.match(source, /console-topbar settlement-topbar/)
  assert.match(source, /console-content settlement-content/)
  assert.match(source, /navigationGroups/)
  assert.match(source, /dashboardKpis/)
  assert.match(source, /workItems/)
  assert.match(source, /agingBuckets/)
  assert.match(source, /loadGeneration/)
  assert.match(source, /generation !== loadGeneration/)
  assert.doesNotMatch(source, /示例客户|mockReceivable|演示数据/)
})

test('Settlement view ships Phase A/B/C UI optimization helpers and components', async () => {
  const view = await readFile(new URL('./views/SettlementView.vue', import.meta.url), 'utf8')
  const css = await readFile(new URL('./styles/settlement.css', import.meta.url), 'utf8')
  const timeline = await readFile(
    new URL('./components/SettlementTimeline.vue', import.meta.url),
    'utf8',
  )
  // Phase B: KPI amount shortener + 本月 filter
  assert.match(view, /formatSettlementAmount/)
  assert.match(view, /isCurrentMonth/)
  assert.match(view, /currentMonthReceipts/)
  assert.match(view, /\$\{currentMonthReceipts\.length\} 笔本月回款/)
  // Phase B.1: dashboardKpis + dunningKpis both use the shortener
  assert.match(view, /value: formatSettlementAmount\(\s*\n?\s*receivables\.value\.reduce/)
  // Phase C: SettlementTimeline component + invoice timeline wiring
  assert.match(view, /import SettlementTimeline/)
  assert.match(view, /<SettlementTimeline :events="invoiceTimelineEvents"/)
  assert.match(timeline, /settlement-timeline-event/)
  assert.match(timeline, /tone-(success|warning|danger|info|purple)/)
  // Phase C.6: 我的待办 section rebuilt as grouped task list
  assert.match(view, /taskGroups/)
  assert.match(view, /settlement-task-item/)
  // Phase A: CSS variables + interactive micro-states
  assert.match(css, /var\(--green, #16a34a\)/)
  assert.match(css, /var\(--orange, #d97706\)/)
  assert.match(css, /var\(--red, #dc2626\)/)
  assert.match(css, /var\(--purple-text, #6d28d9\)/)
  assert.match(css, /animation: settlement-fade-in \.25s ease-out/)
  assert.match(css, /\.settlement-panel table tbody tr:hover/)
  assert.match(css, /translateY\(-2px\)/)
  assert.match(css, /translateY\(-1px\)/)
})
